USE [master]
GO
CREATE LOGIN [Pizzas] WITH PASSWORD=N'Pizzas', DEFAULT_DATABASE=[DAI-Pizzas], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [DAI-Pizzas]
GO
CREATE USER [Pizzas] FOR LOGIN [Pizzas]
GO
USE [DAI-Pizzas]
GO
ALTER ROLE [db_owner] ADD MEMBER [Pizzas]
GO
